echo "os:      $(. /etc/os-release && echo "$PRETTY_NAME")"
echo "node:    $(command -v node >/dev/null && node -v || echo none)"
echo "pnpm:    $(command -v pnpm >/dev/null && pnpm -v || echo none)"
echo "pm2:     $(command -v pm2 >/dev/null && pm2 -v || echo none)"
echo "nginx:   $(command -v nginx >/dev/null && nginx -v 2>&1 | cut -d/ -f2 || echo none)"
echo "cpu:     $(nproc) cores   ram: $(free -m | awk '/Mem:/{print $2}') MB total, $(free -m | awk '/Mem:/{print $7}') MB free"
echo "disk:    $(df -h / | awk 'NR==2{print $4" free of "$2}')"
echo "port 3100: $(ss -ltn 2>/dev/null | grep -q ':3100 ' && echo IN USE || echo free)"
echo "/opt/vgml-service: $([ -d /opt/vgml-service ] && echo exists || echo absent)"
