#!/usr/bin/env bash
#
#  A throwaway administrator for one test run.
#
#  The UI suite has to sign in, and the alternative to this is a real password
#  living in a secret somewhere -- which is a standing key to the box in
#  exchange for a convenience. This makes one for the run and removes it after,
#  so what exists between runs is nothing.
#
#      ACTION=create UI_USER=... UI_PASS=... bash box-ui-user.sh
#      ACTION=delete UI_USER=...             bash box-ui-user.sh
#
#  The password is generated by the caller and masked in its logs; it is never
#  echoed here.
set -euo pipefail

ACTION="${ACTION:-create}"
UI_USER="${UI_USER:?a username is required}"

cd /var/www/wp 2>/dev/null || { echo "no WordPress at /var/www/wp" >&2; exit 1; }
WP="wp --allow-root"

case "$ACTION" in
	create)
		UI_PASS="${UI_PASS:?a password is required}"
		if $WP user get "$UI_USER" --field=ID >/dev/null 2>&1; then
			$WP user update "$UI_USER" --user_pass="$UI_PASS" --role=administrator >/dev/null
			echo "reused the existing test administrator"
		else
			$WP user create "$UI_USER" "${UI_USER}@invalid.test" \
				--role=administrator --user_pass="$UI_PASS" >/dev/null
			echo "created a test administrator"
		fi
		;;
	delete)
		if $WP user get "$UI_USER" --field=ID >/dev/null 2>&1; then
			$WP user delete "$UI_USER" --yes >/dev/null
			echo "removed the test administrator"
		else
			echo "no test administrator to remove"
		fi
		;;
	*)
		echo "ACTION must be create or delete" >&2
		exit 1
		;;
esac
